import { ALL_STATUS_OPTIONS_KEY, ALL_STOPS_STATUS_OPTIONS_KEY } from "./dispatch-table-constants";
import { KMA_KEYS, type DispatchResponsePayload } from "./dispatch-table.types";

export const dispatchListOk: DispatchResponsePayload[] = [
      {
        id: 100,
        status: ALL_STATUS_OPTIONS_KEY.OPEN,
        customerLoadNumber: 76755444,
        loadNumber: "681522",
        customer: "Target",
        shipper: "PepsiCo, Inc",
        city: "Bloomingdale, GA",
        numberOfStops: "2",
        totalMiles: 892,
        shippedPallets: 25,
        rateType: "tl",
        pickupDate: "2024-10-08T08:30:00.000Z",
        stopStatus: ALL_STOPS_STATUS_OPTIONS_KEY.APPOINTMENT,
        kma: KMA_KEYS.NF_STJ,
        carrier: "",
        destination: "Atlanta",
        shippedCube: 1500,
      },
      {
        id: 101,
        status: ALL_STATUS_OPTIONS_KEY.OPEN,
        customerLoadNumber: 76755344,
        loadNumber: "681522",
        customer: "Target",
        shipper: "PepsiCo, Inc",
        city: "Bloomingdale, GA",
        numberOfStops: "2",
        totalMiles: 892,
        shippedPallets: 25,
        rateType: "tl",
        pickupDate: "2024-10-08T08:30:00.000Z",
        stopStatus: ALL_STOPS_STATUS_OPTIONS_KEY.ARRIVAL_LATE,
        kma: KMA_KEYS.AR_LIT,
        carrier: "",
        destination: "Atlanta",
        shippedCube: 1500,
      },
      {
        id: 1000,
        status: ALL_STATUS_OPTIONS_KEY.OPEN,
        customerLoadNumber: 76755344,
        loadNumber: "681523",
        customer: "Target",
        shipper: "PepsiCo, Inc",
        city: "Dublin, GA",
        numberOfStops: "3",
        totalMiles: 892,
        shippedPallets: 25,
        rateType: "tl",
        pickupDate: "2024-10-08T08:30:00.000Z",
        stopStatus: "" as keyof typeof ALL_STOPS_STATUS_OPTIONS_KEY,
        kma: KMA_KEYS.CA_LAX,
        carrier: "",
        destination: "Atlanta",
        shippedCube: 1500,
        multistop: [
          {
            id: 10001,
            status: ALL_STATUS_OPTIONS_KEY.PICKUP,
            customerLoadNumber: 767553441,
            loadNumber: "6815221",
            customer: "Walmart",
            shipper: "PepsiCo, Inc",
            city: "Dublin, GA",
            numberOfStops: "3",
            totalMiles: 892,
            shippedPallets: 2,
            rateType: "tl",
            pickupDate: "2024-10-08T08:30:00.000Z",
            kma: KMA_KEYS.CA_LAX,
            carrier: "",
            destination: "-",
            shippedCube: 1500,
            stopStatus: ALL_STOPS_STATUS_OPTIONS_KEY.APPOINTMENT_WARNING,
          },
          {
            id: 10002,
            status: ALL_STATUS_OPTIONS_KEY.PICKUP,
            customerLoadNumber: 767553442,
            loadNumber: "6815222",
            customer: "Walmart",
            shipper: "Mohawkcal",
            city: "Atlanta",
            numberOfStops: "3",
            totalMiles: 890,
            shippedPallets: 23,
            rateType: "tl",
            pickupDate: "2024-10-08T08:30:00.000Z",
            kma: KMA_KEYS.IL_CHI,
            carrier: "",
            destination: "-",
            shippedCube: 1500,
            stopStatus: ALL_STOPS_STATUS_OPTIONS_KEY.DEPARTURE,
          },
          {
            id: 10003,
            status: ALL_STATUS_OPTIONS_KEY.DELIVERY,
            customerLoadNumber: 767553443,
            loadNumber: "6815223",
            customer: "Walmart",
            shipper: "PepsiCo, Inc",
            city: "-",
            numberOfStops: "3",
            totalMiles: 90,
            shippedPallets: 23,
            rateType: "tl",
            pickupDate: "2024-10-08T08:30:00.000Z",
            kma: KMA_KEYS.IL_CHI,
            carrier: "",
            destination: "Atlanta",
            shippedCube: 450,
            stopStatus: ALL_STOPS_STATUS_OPTIONS_KEY.ON_TIME,
          },
        ],
      },
      {
        id: 1001,
        status: ALL_STATUS_OPTIONS_KEY.CUSTOMER_TENDER,
        customerLoadNumber: 38838618,
        loadNumber: "543753",
        customer: "Target",
        shipper: "Mohawkcal",
        city: "Bloomingdale, GA",
        numberOfStops: "2",
        totalMiles: 49,
        shippedPallets: 50,
        rateType: "ltl",
        pickupDate: "2024-10-08T14:30:00.000Z",
        kma: KMA_KEYS.FL_LAK,
        carrier: "",
        destination: "Dallas",
        shippedCube: 450,
        stopStatus: ALL_STOPS_STATUS_OPTIONS_KEY.APPOINTMENT,
      },
      {
        id: 1004,
        status: ALL_STATUS_OPTIONS_KEY.OPEN,
        customerLoadNumber: 94773281,
        loadNumber: "158702",
        customer: "Grainger",
        shipper: "Mohawkcal",
        city: "Aurora, CO",
        numberOfStops: "2",
        totalMiles: 133,
        shippedPallets: 12,
        rateType: "ltl",
        pickupDate: "2024-10-08T09:45:00.000Z",
        kma: KMA_KEYS.FL_LAK,
        carrier: "",
        destination: "Atlanta",
        shippedCube: 1230,
        stopStatus: ALL_STOPS_STATUS_OPTIONS_KEY.ARRIVAL,
      },
      {
        id: 1005,
        status: ALL_STATUS_OPTIONS_KEY.OPEN,
        customerLoadNumber: 94773281,
        loadNumber: "158702",
        customer: "Grainger",
        shipper: "Mohawkcal",
        city: "Aurora, CO",
        numberOfStops: "2",
        totalMiles: 133,
        shippedPallets: 12,
        rateType: "ltl",
        pickupDate: "2024-11-08T09:45:00.000Z",
        kma: KMA_KEYS.FL_LAK,
        carrier: "",
        destination: "Atlanta",
        shippedCube: 1230,
        stopStatus: ALL_STOPS_STATUS_OPTIONS_KEY.ARRIVAL,
      },
      {
        id: 1007,
        status: ALL_STATUS_OPTIONS_KEY.OPEN,
        customerLoadNumber: 88307848,
        loadNumber: "802148",
        customer: "Grainger",
        shipper: "Mohawkcal",
        city: "Dublin, GA",
        numberOfStops: "2",
        totalMiles: 295,
        shippedPallets: 18,
        rateType: "tl",
        pickupDate: "2024-10-08T11:15:00.000Z",
        kma: KMA_KEYS.IL_CHI,
        carrier: "",
        destination: "Atlanta",
        shippedCube: 2300,
        stopStatus: ALL_STOPS_STATUS_OPTIONS_KEY.APPOINTMENT_WARNING,
      },
      {
        id: 10010,
        status: ALL_STATUS_OPTIONS_KEY.OFFERED,
        customerLoadNumber: 48512707,
        loadNumber: "071613",
        customer: "Target",
        shipper: "PepsiCo, Inc",
        city: "Springfield, MO",
        numberOfStops: "2",
        totalMiles: 79,
        shippedPallets: 20,
        rateType: "tl",
        pickupDate: "2024-10-08T08:00:00.000Z",
        kma: KMA_KEYS.FL_TAL,
        carrier: "",
        destination: "Atlanta",
        shippedCube: 1500,
        stopStatus: ALL_STOPS_STATUS_OPTIONS_KEY.DEPARTURE_WARNING,
      },
      {
        id: 10011,
        status: ALL_STATUS_OPTIONS_KEY.OFFERED,
        customerLoadNumber: 81345126,
        loadNumber: "101073",
        customer: "Grainger",
        shipper: "PepsiCo, Inc",
        city: "Raleigh, NC",
        numberOfStops: "2",
        totalMiles: 628,
        shippedPallets: 7,
        rateType: "ltl",
        pickupDate: "2024-10-08T13:30:00.000Z",
        kma: KMA_KEYS.FL_TAL,
        carrier: "",
        destination: "Dallas",
        shippedCube: 450,
        stopStatus: ALL_STOPS_STATUS_OPTIONS_KEY.DEPARTURE_LATE,
      },
      {
        id: 10012,
        status: ALL_STATUS_OPTIONS_KEY.OFFERED,
        customerLoadNumber: 59092069,
        loadNumber: "864128",
        customer: "Target",
        shipper: "PepsiCo, Inc",
        city: "Denver, CO",
        numberOfStops: "2",
        totalMiles: 965,
        shippedPallets: 13,
        rateType: "tl",
        pickupDate: "2024-10-08T10:45:00.000Z",
        kma: KMA_KEYS.FL_TAL,
        carrier: "",
        destination: "Dallas",
        shippedCube: 2000,
        stopStatus: ALL_STOPS_STATUS_OPTIONS_KEY.ON_TIME,
      },
      {
        id: 10013,
        status: ALL_STATUS_OPTIONS_KEY.COVERED,
        customerLoadNumber: 3328926,
        loadNumber: "765400",
        customer: "Target",
        shipper: "Mohawkcal",
        city: "Dublin, GA",
        numberOfStops: "2",
        totalMiles: 320,
        shippedPallets: 21,
        rateType: "tl",
        pickupDate: "2024-10-09T15:20:00.000Z",
        kma: KMA_KEYS.FL_TAL,
        carrier: "",
        destination: "Atlanta",
        shippedCube: 2000,
        stopStatus: "" as keyof typeof ALL_STOPS_STATUS_OPTIONS_KEY,
      },
      {
        id: 10014,
        status: ALL_STATUS_OPTIONS_KEY.COVERED,
        customerLoadNumber: 30843268,
        loadNumber: "932687",
        customer: "Grainger",
        shipper: "PepsiCo, Inc",
        city: "Denver, CO",
        numberOfStops: "2",
        totalMiles: 931,
        shippedPallets: 40,
        rateType: "ltl",
        pickupDate: "2024-10-09T15:45:00.000Z",
        kma: KMA_KEYS.FL_TAL,
        carrier: "",
        destination: "Dallas",
        shippedCube: 2000,
        stopStatus: "" as keyof typeof ALL_STOPS_STATUS_OPTIONS_KEY,
      },
      {
        id: 10016,
        status: ALL_STATUS_OPTIONS_KEY.COVERED,
        customerLoadNumber: 93877693,
        loadNumber: "791936",
        customer: "Grainger",
        shipper: "PepsiCo, Inc",
        city: "Nueva Orleans, LA",
        numberOfStops: "2",
        totalMiles: 224,
        shippedPallets: 62,
        rateType: "ltl",
        pickupDate: "2024-10-11T09:00:00.000Z",
        kma: KMA_KEYS.IA_DES,
        carrier: "",
        destination: "Atlanta",
        shippedCube: 1500,
        stopStatus: "" as keyof typeof ALL_STOPS_STATUS_OPTIONS_KEY,
      },
      {
        id: 10019,
        status: ALL_STATUS_OPTIONS_KEY.IN_TRANSIT,
        customerLoadNumber: 50634666,
        loadNumber: "663960",
        customer: "Target",
        shipper: "Mohawkcal",
        city: "Springfield, MO",
        numberOfStops: "2",
        totalMiles: 814,
        shippedPallets: 58,
        rateType: "tl",
        pickupDate: "2024-10-13T14:30:00.000Z",
        kma: KMA_KEYS.IA_DES,
        carrier: "",
        destination: "Atlanta",
        shippedCube: 450,
        stopStatus: "" as keyof typeof ALL_STOPS_STATUS_OPTIONS_KEY,
      },
      {
        id: 10020,
        status: ALL_STATUS_OPTIONS_KEY.IN_TRANSIT,
        customerLoadNumber: 91718167,
        loadNumber: "909909",
        customer: "Target",
        shipper: "PepsiCo, Inc",
        city: "Mebane, NC",
        numberOfStops: "2",
        totalMiles: 24,
        shippedPallets: 54,
        rateType: "tl",
        pickupDate: "2024-10-16T11:45:00.000Z",
        kma: KMA_KEYS.FL_TAL,
        carrier: "",
        destination: "Atlanta",
        shippedCube: 450,
        stopStatus: ALL_STOPS_STATUS_OPTIONS_KEY.ARRIVAL_LATE,
      },
      {
        id: 10021,
        status: ALL_STATUS_OPTIONS_KEY.IN_TRANSIT,
        customerLoadNumber: 9210813,
        loadNumber: "621335",
        customer: "Target",
        shipper: "Mohawkcal",
        city: "Meba, NC",
        numberOfStops: "2",
        totalMiles: 69,
        shippedPallets: 6,
        rateType: "tl",
        pickupDate: "2024-10-16T08:15:00.000Z",
        kma: KMA_KEYS.FL_TAL,
        carrier: "",
        destination: "Atlanta",
        shippedCube: 450,
        stopStatus: ALL_STOPS_STATUS_OPTIONS_KEY.ARRIVAL_WARNING,
      },
      {
        id: 10022,
        status: ALL_STATUS_OPTIONS_KEY.IN_TRANSIT,
        customerLoadNumber: 98359814,
        loadNumber: "217962",
        customer: "Target",
        shipper: "PepsiCo, Inc",
        city: "Nueva Orleans, LA",
        numberOfStops: "2",
        totalMiles: 622,
        shippedPallets: 10,
        rateType: "ltl",
        pickupDate: "2024-10-17T16:30:00.000Z",
        kma: KMA_KEYS.FL_TAL,
        carrier: "FNAT",
        destination: "Atlanta",
        shippedCube: 1500,
        stopStatus: ALL_STOPS_STATUS_OPTIONS_KEY.DEPARTURE,
      },
      {
        id: 10023,
        status: ALL_STATUS_OPTIONS_KEY.IN_TRANSIT,
        customerLoadNumber: 81985432,
        loadNumber: "626175",
        customer: "Target",
        shipper: "PepsiCo, Inc",
        city: "Raleigh, NC",
        numberOfStops: "2",
        totalMiles: 183,
        shippedPallets: 4,
        rateType: "tl",
        pickupDate: "2024-10-17T10:00:00.000Z",
        kma: KMA_KEYS.TX_FTW,
        carrier: "COUD",
        destination: "Dallas",
        shippedCube: 450,
        stopStatus: "" as keyof typeof ALL_STOPS_STATUS_OPTIONS_KEY,
      },
      {
        id: 10024,
        status: ALL_STATUS_OPTIONS_KEY.IN_TRANSIT,
        customerLoadNumber: 30843233,
        loadNumber: "932688",
        customer: "Target",
        shipper: "PepsiCo, Inc",
        city: "Aurora, CO",
        numberOfStops: "2",
        totalMiles: 931,
        shippedPallets: 3,
        rateType: "ltl",
        pickupDate: "2024-10-17T15:45:00.000Z",
        kma: KMA_KEYS.FL_TAL,
        carrier: "TUAN",
        destination: "Dallas",
        shippedCube: 1230,
        stopStatus: "" as keyof typeof ALL_STOPS_STATUS_OPTIONS_KEY,
      },
      {
        id: 10025,
        status: ALL_STATUS_OPTIONS_KEY.DELIVERED,
        customerLoadNumber: 30343263,
        loadNumber: "932689",
        customer: "Grainger",
        shipper: "PepsiCo, Inc",
        city: "Denver, CO",
        numberOfStops: "2",
        totalMiles: 931,
        shippedPallets: 3,
        rateType: "ltl",
        pickupDate: "2024-10-18T15:45:00.000Z",
        kma: KMA_KEYS.FL_TAL,
        carrier: "COUD",
        destination: "Dallas",
        shippedCube: 1230,
        stopStatus: "" as keyof typeof ALL_STOPS_STATUS_OPTIONS_KEY,
      },
      {
        id: 10026,
        status: ALL_STATUS_OPTIONS_KEY.OPEN,
        customerLoadNumber: 30843264,
        loadNumber: "932696",
        customer: "Grainger",
        shipper: "PepsiCo, Inc",
        city: "Denver, CO",
        numberOfStops: "2",
        totalMiles: 931,
        shippedPallets: 3,
        rateType: "ltl",
        pickupDate: "2024-10-18T15:45:00.000Z",
        kma: KMA_KEYS.FL_TAL,
        carrier: "COUD",
        destination: "Atlanta",
        shippedCube: 1230,
        stopStatus: "" as keyof typeof ALL_STOPS_STATUS_OPTIONS_KEY,
      },
      {
        id: 10027,
        status: ALL_STATUS_OPTIONS_KEY.OPEN,
        customerLoadNumber: 34594196,
        loadNumber: "304356",
        customer: "Grainger",
        shipper: "PepsiCo, Inc",
        city: "Aurora, CO",
        numberOfStops: "2",
        totalMiles: 202,
        shippedPallets: 33,
        rateType: "tl",
        pickupDate: "2024-10-18T13:45:00.000Z",
        kma: KMA_KEYS.FL_TAL,
        carrier: "FNAT",
        destination: "Dallas",
        shippedCube: 1230,
        stopStatus: "" as keyof typeof ALL_STOPS_STATUS_OPTIONS_KEY,
      },
      {
        id: 10029,
        status: ALL_STATUS_OPTIONS_KEY.OPEN,
        customerLoadNumber: 49250758,
        loadNumber: "090281",
        customer: "Grainger",
        shipper: "Mohawkcal",
        city: "Dublin, GA",
        numberOfStops: "2",
        totalMiles: 867,
        shippedPallets: 10,
        rateType: "ltl",
        pickupDate: "2024-10-20T10:30:00.000Z",
        kma: KMA_KEYS.FL_TAL,
        carrier: "COUD",
        destination: "Atlanta",
        shippedCube: 1230,
        stopStatus: "" as keyof typeof ALL_STOPS_STATUS_OPTIONS_KEY,
      },
      {
        id: 10030,
        status: ALL_STATUS_OPTIONS_KEY.INVOICED,
        customerLoadNumber: 93243444,
        loadNumber: "270119",
        customer: "Target",
        shipper: "Mohawkcal",
        city: "Nueva Orleans, LA",
        numberOfStops: "2",
        totalMiles: 790,
        shippedPallets: 20,
        rateType: "tl",
        pickupDate: "2024-10-21T14:15:00.000Z",
        kma: KMA_KEYS.NC_GRE,
        carrier: "COUD",
        destination: "Atlanta",
        shippedCube: 1230,
        stopStatus: "" as keyof typeof ALL_STOPS_STATUS_OPTIONS_KEY,
      },
      {
        id: 10031,
        status: ALL_STATUS_OPTIONS_KEY.INVOICED,
        customerLoadNumber: 98975786,
        loadNumber: "250785",
        customer: "Target",
        shipper: "PepsiCo, Inc",
        city: "Springfield, MO",
        numberOfStops: "2",
        totalMiles: 533,
        shippedPallets: 15,
        rateType: "ltl",
        pickupDate: "2024-10-08T09:00:00.000Z",
        kma: KMA_KEYS.FL_TAL,
        carrier: "COUD",
        destination: "Dallas",
        shippedCube: 450,
        stopStatus: "" as keyof typeof ALL_STOPS_STATUS_OPTIONS_KEY,
      },
      {
        id: 10032,
        status: ALL_STATUS_OPTIONS_KEY.INVOICED,
        customerLoadNumber: 30843265,
        loadNumber: "932686",
        customer: "Target",
        shipper: "PepsiCo, Inc",
        city: "Aurora, CO",
        numberOfStops: "2",
        totalMiles: 931,
        shippedPallets: 5,
        rateType: "ltl",
        pickupDate: "2024-10-08T09:00:00.000Z",
        kma: KMA_KEYS.TX_FTW,
        carrier: "TUAN",
        destination: "Dallas",
        shippedCube: 1500,
        stopStatus: "" as keyof typeof ALL_STOPS_STATUS_OPTIONS_KEY,
      },
      {
        id: 10033,
        status: ALL_STATUS_OPTIONS_KEY.IN_TRANSIT,
        customerLoadNumber: 30843266,
        loadNumber: "932676",
        customer: "Grainger",
        shipper: "PepsiCo, Inc",
        city: "Denver, CO",
        numberOfStops: "2",
        totalMiles: 931,
        shippedPallets: 4,
        rateType: "ltl",
        pickupDate: "2024-10-08T09:00:00.000Z",
        kma: KMA_KEYS.NC_GRE,
        carrier: "COUD",
        destination: "Dallas",
        shippedCube: 1500,
        stopStatus: "" as keyof typeof ALL_STOPS_STATUS_OPTIONS_KEY,
      },
      {
        id: 10034,
        status: ALL_STATUS_OPTIONS_KEY.IN_TRANSIT,
        customerLoadNumber: 30843267,
        loadNumber: "932666",
        customer: "Target",
        shipper: "PepsiCo, Inc",
        city: "Denver, CO",
        numberOfStops: "2",
        totalMiles: 931,
        shippedPallets: 4,
        rateType: "ltl",
        pickupDate: "2024-10-08T09:00:00.000Z",
        kma: KMA_KEYS.FL_TAL,
        carrier: "COUD",
        destination: "Atlanta",
        shippedCube: 1500,
        stopStatus: "" as keyof typeof ALL_STOPS_STATUS_OPTIONS_KEY,
      },
      {
        id: 10035,
        status: ALL_STATUS_OPTIONS_KEY.IN_TRANSIT,
        customerLoadNumber: 59301989,
        loadNumber: "101084",
        customer: "Target",
        shipper: "Mohawkcal",
        city: "Raleigh, NC",
        numberOfStops: "2",
        totalMiles: 827,
        shippedPallets: 8,
        rateType: "tl",
        pickupDate: "2024-10-08T09:00:00.000Z",
        kma: KMA_KEYS.FL_TAL,
        carrier: "COUD",
        destination: "Dallas",
        shippedCube: 450,
        stopStatus: "" as keyof typeof ALL_STOPS_STATUS_OPTIONS_KEY,
      },
      {
        id: 10036,
        status: ALL_STATUS_OPTIONS_KEY.OFFERED,
        customerLoadNumber: 30843260,
        loadNumber: "934686",
        customer: "Target",
        shipper: "PepsiCo, Inc",
        city: "Denver, CO",
        numberOfStops: "2",
        totalMiles: 931,
        shippedPallets: 40,
        rateType: "ltl",
        pickupDate: "2024-10-08T09:00:00.000Z",
        kma: KMA_KEYS.FL_TAL,
        carrier: "COUD",
        destination: "Dallas",
        shippedCube: 2000,
        stopStatus: "" as keyof typeof ALL_STOPS_STATUS_OPTIONS_KEY,
      },
      {
        id: 10037,
        status: ALL_STATUS_OPTIONS_KEY.REJECTED,
        customerLoadNumber: 30843261,
        loadNumber: "932656",
        customer: "Grainger",
        shipper: "PepsiCo, Inc",
        city: "Denver, CO",
        numberOfStops: "2",
        totalMiles: 931,
        shippedPallets: 20,
        rateType: "ltl",
        pickupDate: "2024-10-08T09:00:00.000Z",
        kma: KMA_KEYS.FL_TAL,
        carrier: "TUAN",
        destination: "Atlanta",
        shippedCube: 1500,
        stopStatus: "" as keyof typeof ALL_STOPS_STATUS_OPTIONS_KEY,
      },
      {
        id: 10038,
        status: ALL_STATUS_OPTIONS_KEY.REJECTED,
        customerLoadNumber: 30843262,
        loadNumber: "932636",
        customer: "Grainger",
        shipper: "PepsiCo, Inc",
        city: "Denver, CO",
        numberOfStops: "2",
        totalMiles: 931,
        shippedPallets: 4,
        rateType: "ltl",
        pickupDate: "2024-10-08T09:00:00.000Z",
        kma: KMA_KEYS.FL_TAL,
        carrier: "COUD",
        destination: "Atlanta",
        shippedCube: 1500,
        stopStatus: ALL_STOPS_STATUS_OPTIONS_KEY.ON_TIME,
      },
      {
        id: 10039,
        status: ALL_STATUS_OPTIONS_KEY.REJECTED,
        customerLoadNumber: 30843263,
        loadNumber: "932646",
        customer: "Target",
        shipper: "PepsiCo, Inc",
        city: "Denver, CO",
        numberOfStops: "2",
        totalMiles: 931,
        shippedPallets: 13,
        rateType: "ltl",
        pickupDate: "2024-10-08T09:00:00.000Z",
        kma: KMA_KEYS.FL_TAL,
        carrier: "FNAT",
        destination: "Atlanta",
        shippedCube: 1230,
        stopStatus: "" as keyof typeof ALL_STOPS_STATUS_OPTIONS_KEY,
      },
    ];
    // size: NUMERICS.PAGE_SIZE_25,
    // page: 0,
    // sort: "ID",
    // order: "ASC",
    // search: "",
    // count: NUMERICS.PAGE_SIZE_25,